import Styles from "../styles/about.module.css";
import Head from "next/head";
function about() {
  return (
    <>
      <Head>
        <title>Jared McCarver - About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={Styles.Wrapper}>
        <h1>About Me</h1>
        <p>
          I am an aspiring Software Engineer with 2 years of experience with
          React Js and web development. I currently work at Stewart Engineer
          where I am designing a web app in Next JS that will be used to model
          and automate glass coatings. I am managing the project and am helping
          teach an intern React JS, HTML, CSS, Python and Git so they may help
          me.
        </p>
        <p>
          I graduated from North Carolina State University in May 2021 with
          degrees in Electrical Engineering and Computer Engineering. My
          concentration included Computer Architecture, Signals and Systems, and
          computer networking. I conducted my senior design project with IBM.
          The project was to develop a web app in React JS that communicated
          with a Python Tiling API and Java Rest Service. We then Dockerized
          each section and got it running end to end in Kubernetes.
        </p>
        <h1 className={Styles.HText}>Programming Skills</h1>
        <div className={Styles.SkillList}>
          <div>
            <h3>Proficient</h3>
            <ul className={Styles.Skills}>
              <li>React JS</li>
              <li>Next JS</li>
              <li>HTML5</li>
              <li>CSS</li>
              <li>Javascript</li>
              <li>Python</li>
            </ul>
          </div>
          <div>
            <h3>Intermediate</h3>
            <ul className={Styles.Skills}>
              <li>Java</li>
              <li>C++</li>
              <li>C#</li>
              <li></li>
            </ul>
          </div>
          <div>
            <h3>Beginner</h3>
            <ul className={Styles.Skills}>
              <li>C</li>
              <li>PHP</li>
              <li>Rust</li>
              <li></li>
            </ul>
          </div>
        </div>
      </div>
    </>
  );
}
export default about;
