import Styles from "../styles/about.module.css";
import Head from "next/head";
function about() {
  return (
    <>
      <Head>
        <title>Jared McCarver - About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={Styles.Wrapper}>
        <h1>About Me</h1>
        <p>
          I am an aspiring Software Engineer with 2 years of experience with
          React Js and web development. I currently work at Stewart Engineers
          where I am designing a web app in Next JS that will be used to model
          and automate glass coatings. I am managing the project and am helping
          teach an intern React JS, HTML, CSS, Python and Git so they may help
          me.
        </p>
        <p>
          I graduated from North Carolina State University in May 2021 with
          degrees in Electrical Engineering and Computer Engineering. My
          concentration included Computer Architecture, Signals and Systems, and
          computer networking. I conducted my senior design project with IBM.
          The project was to develop a web app in React JS that communicated
          with a Python Tiling API and Java Rest Service. We then Dockerized
          each section and got it running end to end in Kubernetes.
        </p>
        <p>
          I am currently most interested in learning Django and how to build a
          machine learning API that I will be able to integrate with the coating
          automation software for my current employer.
        </p>
        <div className={Styles.Skills}>
          <div>
            <h1>Programming Skills</h1>
            <div>
              <div>
                <h3>Proficient</h3>
                <ul>
                  <li>React JS</li>
                  <li>Next JS</li>
                  <li>HTML5</li>
                  <li>CSS</li>
                  <li>JS</li>
                  <li>Python</li>
                </ul>
              </div>
              <div>
                <h3>Intermediate</h3>
                <ul>
                  <li>Java</li>
                  <li>C++</li>
                  <li>C#</li>
                  <li>C</li>
                  <li>Django</li>
                </ul>
              </div>
            </div>
          </div>
          <div>
            <h1>Development Skills</h1>
            <div>
              <div>
                <h3>Proficient</h3>
                <ul>
                  <li>Git</li>
                  <li>AWS</li>
                  <li>Heroku</li>
                  <li>Eclipse</li>
                </ul>
              </div>
              <div>
                <h3>Intermediate</h3>
                <ul>
                  <li>Docker</li>
                  <li>Kubernetes</li>
                  <li>Wordpress</li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
export default about;
