import Head from "next/head";
import Styles from "../styles/Home.module.css";
import Link from "next/link";
export default function Home() {
  const Projects = [
    {
      Name: "Freeman Pet Shop",
      Link: "https://jmccarver.com/projects",
      img: "./Allyson_site_thumb.png",
    },
    {
      Name: "Jared McCarver",
      Link: "https://allysonfreeman.com/",
      img: "./Jared_site_thumb.png",
    },
    {
      Name: "Allyson Freeman",
      Link: "https://allysonfreeman.com/",
      img: "./Allyson_site_thumb.png",
    },
  ];
  return (
    <>
      <Head>
        <title>Jared McCarver - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={Styles.Home}>
          <div className={Styles.Intro}>
            <div className={Styles["Intro-text"]}>
              <div>
                <h1>I will design and develop your Websites and Apps</h1>
                <h3>
                  Hi, My name is Jared and I am an aspiring web developer. I
                  will work diligently using my skills to build the best website
                  for you!
                </h3>
                <Link href="/#projects">
                  <a>
                    <button>View My Work</button>
                  </a>
                </Link>
              </div>
              <div>
                <img src="./Work_Home.svg"></img>
              </div>
            </div>
          </div>
          <div className={Styles.BriefIntro}>
            <h1>Lorem Ipsum Ipsum</h1>
            <h3>
              Lorem Ipsum is simply dummy text of the printing and typesetting
              industry. Lorem Ipsum has been the industry's standard dummy text
              ever since the 1500s, when an unknown
            </h3>
          </div>
          <div className={Styles.FeaturedProjects}>
            <h1>Featured Projects</h1>
            <div className={Styles.Cards}>
              {Projects.map((Project) => (
                <div className={Styles.Project}>
                  <img src={Project.img}></img>
                  <div className={Styles["Project-text"]}>
                    <a href={Project.Link}>
                      <h3>{Project.Name}</h3>
                    </a>
                    <p>Basic sumamry for now</p>
                  </div>
                </div>
              ))}
            </div>
            <button>All Projects</button>
          </div>
        </div>
      </main>
    </>
  );
}
