import Head from "next/head";
import Styles from "../styles/Home.module.css";
import ProjectList from "../Components/ProjectList";
import Link from "next/link";
export default function Home() {
  return (
    <>
      <Head>
        <title>Jared McCarver - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={Styles.Home}>
          <div className={Styles.Intro}>
            <div className={Styles["Intro-text"]}>
              <div>
                <h1>I will design and develop your Websites and Apps</h1>
                <h3>
                  Hi, My name is Jared and I am an aspiring web developer. I
                  will work diligently using my skills to build the best website
                  for you!
                </h3>
                <Link href="/#projects">
                  <a>
                    <button>View My Work</button>
                  </a>
                </Link>
              </div>
              <div>
                <img src="./Work_Home.svg"></img>
              </div>
            </div>
          </div>
          <div id="projects">
            <ProjectList />
          </div>
          <div className={Styles.contactwrapper} id="contact">
            <h1>Contact Me</h1>
            <div  className={Styles.contact}>
              <div>
                <h3>Send Me A Message</h3>
                <p>If you would like to contact</p>
              </div>

              <form
                className={Styles.contactform}
                action="https://submit-form.com/QObGMX5B"
              >
                <div className={Styles.contactinputs}>
                  <input
                    type="hidden"
                    name="_redirect"
                    value="https://localhost:3000/thanks"
                  />
                  <input
                    type="text"
                    id="name"
                    name="name"
                    placeholder="Jared McCarver"
                    required=""
                  />
                  <input
                    type="tel"
                    id="tel"
                    name="tel"
                    placeholder="Phone Number"
                    required=""
                  />
                  <input
                    type="email"
                    id="email"
                    name="email"
                    placeholder="email@example.com"
                    required=""
                  />
                  <button
                    type="submit"
                    onClick={(e) => {
                      e.preventDefault();
                    }}
                    className={Styles.button}
                  >
                    Send Request &#8594;
                  </button>
                </div>
                <div className={Styles.messagebox}>
                  <textarea
                    id="message"
                    name="message"
                    placeholder="Please enter your message..."
                    required=""
                  ></textarea>
                </div>
              </form>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
