import Head from "next/head";
import Styles from "../styles/Home.module.css";
import Link from "next/link";
import WorkFromHome from "../Components/Work_Home";
export default function Home() {
  const Projects = [
    {
      Name: "Freeman Pet Shop",
      Link: "https://freemanpets.com",
      img: "./Allyson_site_thumb.png",
      description:
        "Simple CRUD forum built in Django to share posts about your pets. Includes adoptions section.",
    },
    {
      Name: "Jared McCarver",
      Link: "https://allysonfreeman.com/",
      img: "./jared_site_thumb.png",
      description: "Personal porfolio built using React and Next JS",
    },
    {
      Name: "Allyson Freeman",
      Link: "https://allysonfreeman.com/",
      img: "./Allyson_site_thumb.png",
      Description:
        "Allyson Freeman GIS Porfolio built in Next that integrates with ESRI API",
    },
  ];
  return (
    <>
      <Head>
        <title>Jared McCarver - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={Styles.Home}>
          <div className={Styles.Intro}>
            <div className={Styles["Intro-text"]}>
              <div>
                <h1>I will design and develop your Websites and Apps</h1>
                <h3>
                  Hi, My name is Jared and I am an aspiring web developer. I
                  will work diligently using my skills to build the best website
                  for you!
                </h3>
                <Link href="/#projects">
                  <a>
                    <button>View My Work</button>
                  </a>
                </Link>
              </div>
              <div>
                <WorkFromHome />
              </div>
            </div>
          </div>
          <div className={Styles.BriefIntro}>
            <h1>A Little About Me.</h1>
            <h3>
              My Name is Jared McCarver. I am a recent graduate of NC State in
              Electrical and Computer Engineering. I currently work at Stewart
              Engineers where I am developing a web app to automate Glass
              Coatings. In my spare time, I love bowling, reading fantasy and
              history books, and spending time with my 3 cats.
            </h3>
          </div>
          <div className={Styles.FeaturedProjects}>
            <h1>Featured Projects</h1>
            <div className={Styles.Cards}>
              {Projects.map((Project) => (
                <div key={Project.Name} className={Styles.Project}>
                  <img src={Project.img}></img>
                  <div className={Styles["Project-text"]}>
                    <a href={Project.Link}>
                      <h3>{Project.Name}</h3>
                    </a>
                    <p>{Project.Description}</p>
                  </div>
                </div>
              ))}
            </div>
            <button>All Projects</button>
          </div>
        </div>
      </main>
    </>
  );
}
